version: "3.7"
services:
  app:
    image: jelab/laravel
    container_name: thetiptop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - thetiptop

  db:
    platform: linux/x86_64
    image: mysql/mysql-server:8.0.23
    container_name: thetiptop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "thetiptop"
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - thetiptop

  nginx:
    image: nginx:alpine
    container_name: thetiptop-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - thetiptop

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    networks:
      - thetiptop

networks:
  thetiptop:
    driver: bridge
